# FROM python:3.11

# WORKDIR /app

# COPY . /app

# RUN apt-get update && \
#     apt-get install -y libasound2-dev portaudio19-dev && \

#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/* && \
#     pip install --no-cache-dir -r requirements.txt

# RUN  apt-get install  -y pulseaudio 

# ENV AUDIODEV /dev/snd

# EXPOSE 80

# CMD ["python3", "detect_cough.py"]
# FROM python:3.11

# WORKDIR /app

# COPY . /app

# RUN apt-get update && \
#     apt-get install -y libasound2-dev libportaudio2 portaudio19-dev && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/* && \
#     pip install --no-cache-dir -r requirements.txt

# ENV AUDIODEV /dev/snd

# EXPOSE 80

# CMD ["python3", "detect_cough.py"]

FROM debian:12

ENV DEBIAN_FRONTEND noninteractive

WORKDIR  /app


COPY . /app


RUN apt-get update

RUN  apt-get -y install software-properties-common wget
RUN apt-get install -y pulseaudio pulseaudio-utils
RUN apt-get install -y libportaudio2 libportaudiocpp0 portaudio19-dev

RUN wget https://www.python.org/ftp/python/3.11.1/Python-3.11.1.tar.xz

RUN apt-get install -y python3-pip

RUN  tar -xf Python-3.11.1.tar.xz

RUN apt-get install -y  python3.11-venv




# Create a virtual environment
RUN python3 -m venv /venv

# Activate the virtual environment
ENV PATH="/venv/bin:$PATH"


RUN pip install -r requirements.txt

ENV PULSE_SERVER=host.docker.internal

# CMD ["python3", "detect_cough.py"]

# RUN cd Python-3.11.1

# RUN  ./configure --enable-optimizations

# RUN  make altinstall

# RUN cd 


